// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    const int c = vlSymsp->__Vm_baseCode;
    tracep->pushPrefix("$rootio", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+1,0,"S_AXI_ACLK",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"S_AXI_ARESETN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+3,0,"S_AXI_AWADDR",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBit(c+4,0,"S_AXI_AWVALID",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+5,0,"S_AXI_AWREADY",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+6,0,"S_AXI_WDATA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+7,0,"S_AXI_WSTRB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+8,0,"S_AXI_WVALID",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+9,0,"S_AXI_WREADY",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+10,0,"S_AXI_BRESP",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+11,0,"S_AXI_BVALID",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+12,0,"S_AXI_BREADY",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+13,0,"S_AXI_ARADDR",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBit(c+14,0,"S_AXI_ARVALID",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"S_AXI_ARREADY",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+16,0,"S_AXI_RDATA",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+17,0,"S_AXI_RRESP",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+18,0,"S_AXI_RVALID",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+19,0,"S_AXI_RREADY",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+20,0,"S_AXIS_TDATA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+21,0,"S_AXIS_TKEEP",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+22,0,"S_AXIS_TLAST",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+23,0,"S_AXIS_TVALID",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+24,0,"S_AXIS_TREADY",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("top_slave_module", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+666,0,"C_S_AXI_DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+667,0,"C_S_AXI_ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+668,0,"PATTERN_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+666,0,"POS_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+669,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+670,0,"FIFO_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+671,0,"MATCH_LATENCY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+25,0,"S_AXI_ACLK",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+26,0,"S_AXI_ARESETN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+27,0,"S_AXI_AWADDR",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBit(c+28,0,"S_AXI_AWVALID",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"S_AXI_AWREADY",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+30,0,"S_AXI_WDATA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+31,0,"S_AXI_WSTRB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+32,0,"S_AXI_WVALID",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"S_AXI_WREADY",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+34,0,"S_AXI_BRESP",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+35,0,"S_AXI_BVALID",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+36,0,"S_AXI_BREADY",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+37,0,"S_AXI_ARADDR",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBit(c+38,0,"S_AXI_ARVALID",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"S_AXI_ARREADY",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+40,0,"S_AXI_RDATA",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+41,0,"S_AXI_RRESP",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+42,0,"S_AXI_RVALID",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"S_AXI_RREADY",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+44,0,"S_AXIS_TDATA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+45,0,"S_AXIS_TKEEP",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+46,0,"S_AXIS_TLAST",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+47,0,"S_AXIS_TVALID",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"S_AXIS_TREADY",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+49,0,"rst_n_meta",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+50,0,"rst_n_sync",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+51,0,"sys_rst_n",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+52,0,"sig_pattern_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1023,0);
    tracep->declArray(c+84,0,"sig_mask_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1023,0);
    tracep->declBus(c+116,0,"sig_pattern_len_full",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+117,0,"sig_operation_mode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+118,0,"sig_final_char_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+119,0,"sig_char_count_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+120,0,"sig_encoding_error",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+121,0,"sig_error_position",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+122,0,"sig_match_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+123,0,"sig_match_count_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+124,0,"sig_fifo_data_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+125,0,"sig_fifo_empty",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"sig_fifo_rd_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+127,0,"sig_pattern_len",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+128,0,"gb_tdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+129,0,"gb_tvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+130,0,"gb_tready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"gb_tlast",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+132,0,"val_tdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+133,0,"val_tpos",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+134,0,"val_tvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"val_tready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"val_tlast",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"matcher_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+138,0,"matcher_tvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+139,0,"matcher_tdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+140,0,"matcher_tpos",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+141,0,"matcher_tlast",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+142,0,"matcher_tready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+143,0,"hit_data_wire",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+144,0,"hit_valid_wire",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+145,0,"fifo_count_wire",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+146,0,"fifo_wr_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("u_axi_lite_regs", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+666,0,"C_S_AXI_DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+667,0,"C_S_AXI_ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+668,0,"PATTERN_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+666,0,"POS_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+147,0,"S_AXI_ACLK",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+148,0,"S_AXI_ARESETN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+149,0,"S_AXI_AWADDR",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBit(c+150,0,"S_AXI_AWVALID",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+151,0,"S_AXI_AWREADY",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+152,0,"S_AXI_WDATA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+153,0,"S_AXI_WSTRB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+154,0,"S_AXI_WVALID",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+155,0,"S_AXI_WREADY",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+156,0,"S_AXI_BRESP",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+157,0,"S_AXI_BVALID",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+158,0,"S_AXI_BREADY",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+159,0,"S_AXI_ARADDR",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBit(c+160,0,"S_AXI_ARVALID",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+161,0,"S_AXI_ARREADY",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+162,0,"S_AXI_RDATA",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+163,0,"S_AXI_RRESP",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+164,0,"S_AXI_RVALID",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+165,0,"S_AXI_RREADY",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+166,0,"pattern_in",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1023,0);
    tracep->declArray(c+198,0,"mask_in",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1023,0);
    tracep->declBus(c+230,0,"pattern_len",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+231,0,"operation_mode",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+232,0,"final_char_count",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+233,0,"char_count_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+234,0,"encoding_error",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+235,0,"error_position",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+236,0,"match_count",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+237,0,"match_count_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+238,0,"fifo_data_out",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+239,0,"fifo_empty",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+240,0,"fifo_rd_en",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+666,0,"PATTERN_REGS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+672,0,"PATTERN_IDX_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+673,0,"ADDR_SHIFT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+674,0,"ADDR_PATTERN_BASE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+675,0,"ADDR_PATTERN_HIGH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+676,0,"ADDR_MASK_BASE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+677,0,"ADDR_MASK_HIGH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+241,0,"axi_awready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+242,0,"axi_wready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+243,0,"axi_bvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+244,0,"axi_arready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+245,0,"axi_rvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+246,0,"axi_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+247,0,"awaddr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+248,0,"axi_araddr_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->pushPrefix("reg_pattern", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+249+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("reg_mask", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+281+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+313,0,"latched_fifo_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+314,0,"latched_data_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+315,0,"sending_valid_fifo_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+316,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+317,0,"byte_index",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+318,0,"slv_reg_wren",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+319,0,"write_pat_offset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+320,0,"write_mask_offset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+321,0,"read_pat_offset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+322,0,"read_mask_offset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBit(c+323,0,"cpu_reads_fifo",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("u_hits_fifo", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+666,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+670,0,"FIFO_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+324,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+325,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+326,0,"data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+327,0,"wr_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+328,0,"rd_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+329,0,"data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+330,0,"empty",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+331,0,"count_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->pushPrefix("mem", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 16; ++i) {
        tracep->declBus(c+332+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+348,0,"wr_ptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+349,0,"rd_ptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+350,0,"count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+351,0,"wr_allowed",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+352,0,"rd_allowed",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("u_stream_gearbox", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+666,0,"DATA_IN_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+669,0,"DATA_OUT_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+678,0,"KEEP_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+353,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+354,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+355,0,"s_axis_tdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+356,0,"s_axis_tkeep",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+357,0,"s_axis_tvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+358,0,"s_axis_tready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+359,0,"s_axis_tlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+360,0,"m_axis_tdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+361,0,"m_axis_tvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+362,0,"m_axis_tlast",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+363,0,"m_axis_tready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+364,0,"buf_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+365,0,"buf_keep",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+366,0,"buf_last",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+367,0,"buf_idx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+368,0,"buf_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+369,0,"max_idx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+370,0,"is_last_byte",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+371,0,"pipe_advance",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+372,0,"ext_byte",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("u_stream_validator", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+669,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+666,0,"POS_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+373,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+374,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+375,0,"s_axis_tdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+376,0,"s_axis_tvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+377,0,"s_axis_tready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+378,0,"s_axis_tlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+379,0,"m_axis_tdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+380,0,"m_axis_tvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+381,0,"m_axis_tlast",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+382,0,"m_current_pos",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+383,0,"m_axis_tready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+384,0,"encoding_error",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+385,0,"error_position",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+386,0,"final_char_count",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+387,0,"char_count_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+388,0,"pipe_advance",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+389,0,"utf8_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+390,0,"char_pos_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+391,0,"is_new_file",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+392,0,"expect_e0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+393,0,"expect_ed",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+394,0,"expect_f0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+395,0,"expect_f4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+396,0,"active_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+397,0,"active_pos",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+398,0,"char_completes_this_byte",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("u_subchar_matcher", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+669,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+670,0,"FIFO_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+668,0,"PATTERN_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+666,0,"POS_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+671,0,"MATCH_LATENCY",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+399,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+400,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+401,0,"s_axis_tvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+402,0,"s_axis_tdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+403,0,"s_axis_tpos",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+404,0,"s_axis_tlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+405,0,"s_axis_tready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+406,0,"pattern_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1023,0);
    tracep->declArray(c+438,0,"mask_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1023,0);
    tracep->declBus(c+470,0,"pattern_len",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+471,0,"matcher_active",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+472,0,"hit_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+473,0,"hit_valid_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+474,0,"fifo_count_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+475,0,"match_count",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+476,0,"match_count_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+679,0,"IDLE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+680,0,"RUNNING",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+681,0,"PAUSED",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+682,0,"FLUSHING",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+672,0,"FLUSH_TARGET",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+683,0,"FLUSH_CNT_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+669,0,"PAT_LEN_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+477,0,"state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+478,0,"next_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+479,0,"flush_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declArray(c+480,0,"shift_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1023,0);
    tracep->declBus(c+512,0,"data_in_fifo",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+513,0,"match_found",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("pos_pipe", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 4; ++i) {
        tracep->declBus(c+514+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+518,0,"pattern_start_offset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+519,0,"clk_en_latch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+520,0,"shift_reg_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+521,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+522,0,"match_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+523,0,"ready_to_accept",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+524,0,"s_axis_txfer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+525,0,"pattern_len_ext",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+526,0,"const_one",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declQuad(c+527,0,"pos_diff_ext",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 32,0);
    tracep->declBit(c+529,0,"datapath_active",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+530,0,"clk_gated",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("wide_comparator_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+668,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+531,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+532,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+533,0,"shift_reg",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1023,0);
    tracep->declArray(c+565,0,"pattern_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1023,0);
    tracep->declArray(c+597,0,"mask_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1023,0);
    tracep->declBit(c+629,0,"data_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+630,0,"match_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+684,0,"CHUNK_SIZE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+669,0,"CHUNKS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declArray(c+631,0,"mismatch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1023,0);
    tracep->declBus(c+663,0,"chunk_match",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+664,0,"valid_pipe",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+665,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullIData(oldp+666,(0x00000020U),32);
    bufp->fullIData(oldp+667,(0x0000000cU),32);
    bufp->fullIData(oldp+668,(0x00000400U),32);
    bufp->fullIData(oldp+669,(8U),32);
    bufp->fullIData(oldp+670,(0x00000010U),32);
    bufp->fullIData(oldp+671,(6U),32);
    bufp->fullIData(oldp+672,(5U),32);
    bufp->fullIData(oldp+673,(2U),32);
    bufp->fullSData(oldp+674,(0x0100U),12);
    bufp->fullIData(oldp+675,(0x00000180U),32);
    bufp->fullSData(oldp+676,(0x0200U),12);
    bufp->fullIData(oldp+677,(0x00000280U),32);
    bufp->fullIData(oldp+678,(4U),32);
    bufp->fullCData(oldp+679,(0U),2);
    bufp->fullCData(oldp+680,(1U),2);
    bufp->fullCData(oldp+681,(2U),2);
    bufp->fullCData(oldp+682,(3U),2);
    bufp->fullIData(oldp+683,(3U),32);
    bufp->fullIData(oldp+684,(0x00000080U),32);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullBit(oldp+1,(vlSelfRef.S_AXI_ACLK));
    bufp->fullBit(oldp+2,(vlSelfRef.S_AXI_ARESETN));
    bufp->fullSData(oldp+3,(vlSelfRef.S_AXI_AWADDR),12);
    bufp->fullBit(oldp+4,(vlSelfRef.S_AXI_AWVALID));
    bufp->fullBit(oldp+5,(vlSelfRef.S_AXI_AWREADY));
    bufp->fullIData(oldp+6,(vlSelfRef.S_AXI_WDATA),32);
    bufp->fullCData(oldp+7,(vlSelfRef.S_AXI_WSTRB),4);
    bufp->fullBit(oldp+8,(vlSelfRef.S_AXI_WVALID));
    bufp->fullBit(oldp+9,(vlSelfRef.S_AXI_WREADY));
    bufp->fullCData(oldp+10,(vlSelfRef.S_AXI_BRESP),2);
    bufp->fullBit(oldp+11,(vlSelfRef.S_AXI_BVALID));
    bufp->fullBit(oldp+12,(vlSelfRef.S_AXI_BREADY));
    bufp->fullSData(oldp+13,(vlSelfRef.S_AXI_ARADDR),12);
    bufp->fullBit(oldp+14,(vlSelfRef.S_AXI_ARVALID));
    bufp->fullBit(oldp+15,(vlSelfRef.S_AXI_ARREADY));
    bufp->fullIData(oldp+16,(vlSelfRef.S_AXI_RDATA),32);
    bufp->fullCData(oldp+17,(vlSelfRef.S_AXI_RRESP),2);
    bufp->fullBit(oldp+18,(vlSelfRef.S_AXI_RVALID));
    bufp->fullBit(oldp+19,(vlSelfRef.S_AXI_RREADY));
    bufp->fullIData(oldp+20,(vlSelfRef.S_AXIS_TDATA),32);
    bufp->fullCData(oldp+21,(vlSelfRef.S_AXIS_TKEEP),4);
    bufp->fullBit(oldp+22,(vlSelfRef.S_AXIS_TLAST));
    bufp->fullBit(oldp+23,(vlSelfRef.S_AXIS_TVALID));
    bufp->fullBit(oldp+24,(vlSelfRef.S_AXIS_TREADY));
    bufp->fullBit(oldp+25,(vlSelfRef.top_slave_module__DOT__S_AXI_ACLK));
    bufp->fullBit(oldp+26,(vlSelfRef.top_slave_module__DOT__S_AXI_ARESETN));
    bufp->fullSData(oldp+27,(vlSelfRef.top_slave_module__DOT__S_AXI_AWADDR),12);
    bufp->fullBit(oldp+28,(vlSelfRef.top_slave_module__DOT__S_AXI_AWVALID));
    bufp->fullBit(oldp+29,(vlSelfRef.top_slave_module__DOT__S_AXI_AWREADY));
    bufp->fullIData(oldp+30,(vlSelfRef.top_slave_module__DOT__S_AXI_WDATA),32);
    bufp->fullCData(oldp+31,(vlSelfRef.top_slave_module__DOT__S_AXI_WSTRB),4);
    bufp->fullBit(oldp+32,(vlSelfRef.top_slave_module__DOT__S_AXI_WVALID));
    bufp->fullBit(oldp+33,(vlSelfRef.top_slave_module__DOT__S_AXI_WREADY));
    bufp->fullCData(oldp+34,(vlSelfRef.top_slave_module__DOT__S_AXI_BRESP),2);
    bufp->fullBit(oldp+35,(vlSelfRef.top_slave_module__DOT__S_AXI_BVALID));
    bufp->fullBit(oldp+36,(vlSelfRef.top_slave_module__DOT__S_AXI_BREADY));
    bufp->fullSData(oldp+37,(vlSelfRef.top_slave_module__DOT__S_AXI_ARADDR),12);
    bufp->fullBit(oldp+38,(vlSelfRef.top_slave_module__DOT__S_AXI_ARVALID));
    bufp->fullBit(oldp+39,(vlSelfRef.top_slave_module__DOT__S_AXI_ARREADY));
    bufp->fullIData(oldp+40,(vlSelfRef.top_slave_module__DOT__S_AXI_RDATA),32);
    bufp->fullCData(oldp+41,(vlSelfRef.top_slave_module__DOT__S_AXI_RRESP),2);
    bufp->fullBit(oldp+42,(vlSelfRef.top_slave_module__DOT__S_AXI_RVALID));
    bufp->fullBit(oldp+43,(vlSelfRef.top_slave_module__DOT__S_AXI_RREADY));
    bufp->fullIData(oldp+44,(vlSelfRef.top_slave_module__DOT__S_AXIS_TDATA),32);
    bufp->fullCData(oldp+45,(vlSelfRef.top_slave_module__DOT__S_AXIS_TKEEP),4);
    bufp->fullBit(oldp+46,(vlSelfRef.top_slave_module__DOT__S_AXIS_TLAST));
    bufp->fullBit(oldp+47,(vlSelfRef.top_slave_module__DOT__S_AXIS_TVALID));
    bufp->fullBit(oldp+48,(vlSelfRef.top_slave_module__DOT__S_AXIS_TREADY));
    bufp->fullBit(oldp+49,(vlSelfRef.top_slave_module__DOT__rst_n_meta));
    bufp->fullBit(oldp+50,(vlSelfRef.top_slave_module__DOT__rst_n_sync));
    bufp->fullBit(oldp+51,(vlSelfRef.top_slave_module__DOT__sys_rst_n));
    bufp->fullWData(oldp+52,(vlSelfRef.top_slave_module__DOT__sig_pattern_in),1024);
    bufp->fullWData(oldp+84,(vlSelfRef.top_slave_module__DOT__sig_mask_in),1024);
    bufp->fullIData(oldp+116,(vlSelfRef.top_slave_module__DOT__sig_pattern_len_full),32);
    bufp->fullCData(oldp+117,(vlSelfRef.top_slave_module__DOT__sig_operation_mode),2);
    bufp->fullIData(oldp+118,(vlSelfRef.top_slave_module__DOT__sig_final_char_count),32);
    bufp->fullBit(oldp+119,(vlSelfRef.top_slave_module__DOT__sig_char_count_valid));
    bufp->fullBit(oldp+120,(vlSelfRef.top_slave_module__DOT__sig_encoding_error));
    bufp->fullIData(oldp+121,(vlSelfRef.top_slave_module__DOT__sig_error_position),32);
    bufp->fullIData(oldp+122,(vlSelfRef.top_slave_module__DOT__sig_match_count),32);
    bufp->fullBit(oldp+123,(vlSelfRef.top_slave_module__DOT__sig_match_count_valid));
    bufp->fullIData(oldp+124,(vlSelfRef.top_slave_module__DOT__sig_fifo_data_out),32);
    bufp->fullBit(oldp+125,(vlSelfRef.top_slave_module__DOT__sig_fifo_empty));
    bufp->fullBit(oldp+126,(vlSelfRef.top_slave_module__DOT__sig_fifo_rd_en));
    bufp->fullCData(oldp+127,(vlSelfRef.top_slave_module__DOT__sig_pattern_len),8);
    bufp->fullCData(oldp+128,(vlSelfRef.top_slave_module__DOT__gb_tdata),8);
    bufp->fullBit(oldp+129,(vlSelfRef.top_slave_module__DOT__gb_tvalid));
    bufp->fullBit(oldp+130,(vlSelfRef.top_slave_module__DOT__gb_tready));
    bufp->fullBit(oldp+131,(vlSelfRef.top_slave_module__DOT__gb_tlast));
    bufp->fullCData(oldp+132,(vlSelfRef.top_slave_module__DOT__val_tdata),8);
    bufp->fullIData(oldp+133,(vlSelfRef.top_slave_module__DOT__val_tpos),32);
    bufp->fullBit(oldp+134,(vlSelfRef.top_slave_module__DOT__val_tvalid));
    bufp->fullBit(oldp+135,(vlSelfRef.top_slave_module__DOT__val_tready));
    bufp->fullBit(oldp+136,(vlSelfRef.top_slave_module__DOT__val_tlast));
    bufp->fullBit(oldp+137,(vlSelfRef.top_slave_module__DOT__matcher_en));
    bufp->fullBit(oldp+138,(vlSelfRef.top_slave_module__DOT__matcher_tvalid));
    bufp->fullCData(oldp+139,(vlSelfRef.top_slave_module__DOT__matcher_tdata),8);
    bufp->fullIData(oldp+140,(vlSelfRef.top_slave_module__DOT__matcher_tpos),32);
    bufp->fullBit(oldp+141,(vlSelfRef.top_slave_module__DOT__matcher_tlast));
    bufp->fullBit(oldp+142,(vlSelfRef.top_slave_module__DOT__matcher_tready));
    bufp->fullIData(oldp+143,(vlSelfRef.top_slave_module__DOT__hit_data_wire),32);
    bufp->fullBit(oldp+144,(vlSelfRef.top_slave_module__DOT__hit_valid_wire));
    bufp->fullCData(oldp+145,(vlSelfRef.top_slave_module__DOT__fifo_count_wire),5);
    bufp->fullBit(oldp+146,(vlSelfRef.top_slave_module__DOT__fifo_wr_en));
    bufp->fullBit(oldp+147,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_ACLK));
    bufp->fullBit(oldp+148,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_ARESETN));
    bufp->fullSData(oldp+149,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_AWADDR),12);
    bufp->fullBit(oldp+150,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_AWVALID));
    bufp->fullBit(oldp+151,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_AWREADY));
    bufp->fullIData(oldp+152,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_WDATA),32);
    bufp->fullCData(oldp+153,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_WSTRB),4);
    bufp->fullBit(oldp+154,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_WVALID));
    bufp->fullBit(oldp+155,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_WREADY));
    bufp->fullCData(oldp+156,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_BRESP),2);
    bufp->fullBit(oldp+157,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_BVALID));
    bufp->fullBit(oldp+158,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_BREADY));
    bufp->fullSData(oldp+159,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_ARADDR),12);
    bufp->fullBit(oldp+160,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_ARVALID));
    bufp->fullBit(oldp+161,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_ARREADY));
    bufp->fullIData(oldp+162,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_RDATA),32);
    bufp->fullCData(oldp+163,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_RRESP),2);
    bufp->fullBit(oldp+164,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_RVALID));
    bufp->fullBit(oldp+165,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_RREADY));
    bufp->fullWData(oldp+166,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__pattern_in),1024);
    bufp->fullWData(oldp+198,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__mask_in),1024);
    bufp->fullIData(oldp+230,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__pattern_len),32);
    bufp->fullCData(oldp+231,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__operation_mode),2);
    bufp->fullIData(oldp+232,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__final_char_count),32);
    bufp->fullBit(oldp+233,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__char_count_valid));
    bufp->fullBit(oldp+234,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__encoding_error));
    bufp->fullIData(oldp+235,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__error_position),32);
    bufp->fullIData(oldp+236,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__match_count),32);
    bufp->fullBit(oldp+237,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__match_count_valid));
    bufp->fullIData(oldp+238,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__fifo_data_out),32);
    bufp->fullBit(oldp+239,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__fifo_empty));
    bufp->fullBit(oldp+240,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__fifo_rd_en));
    bufp->fullBit(oldp+241,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__axi_awready));
    bufp->fullBit(oldp+242,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__axi_wready));
    bufp->fullBit(oldp+243,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__axi_bvalid));
    bufp->fullBit(oldp+244,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__axi_arready));
    bufp->fullBit(oldp+245,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__axi_rvalid));
    bufp->fullIData(oldp+246,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__axi_rdata),32);
    bufp->fullSData(oldp+247,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__awaddr),12);
    bufp->fullSData(oldp+248,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__axi_araddr_reg),12);
    bufp->fullIData(oldp+249,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[0]),32);
    bufp->fullIData(oldp+250,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[1]),32);
    bufp->fullIData(oldp+251,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[2]),32);
    bufp->fullIData(oldp+252,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[3]),32);
    bufp->fullIData(oldp+253,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[4]),32);
    bufp->fullIData(oldp+254,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[5]),32);
    bufp->fullIData(oldp+255,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[6]),32);
    bufp->fullIData(oldp+256,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[7]),32);
    bufp->fullIData(oldp+257,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[8]),32);
    bufp->fullIData(oldp+258,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[9]),32);
    bufp->fullIData(oldp+259,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[10]),32);
    bufp->fullIData(oldp+260,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[11]),32);
    bufp->fullIData(oldp+261,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[12]),32);
    bufp->fullIData(oldp+262,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[13]),32);
    bufp->fullIData(oldp+263,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[14]),32);
    bufp->fullIData(oldp+264,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[15]),32);
    bufp->fullIData(oldp+265,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[16]),32);
    bufp->fullIData(oldp+266,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[17]),32);
    bufp->fullIData(oldp+267,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[18]),32);
    bufp->fullIData(oldp+268,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[19]),32);
    bufp->fullIData(oldp+269,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[20]),32);
    bufp->fullIData(oldp+270,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[21]),32);
    bufp->fullIData(oldp+271,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[22]),32);
    bufp->fullIData(oldp+272,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[23]),32);
    bufp->fullIData(oldp+273,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[24]),32);
    bufp->fullIData(oldp+274,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[25]),32);
    bufp->fullIData(oldp+275,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[26]),32);
    bufp->fullIData(oldp+276,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[27]),32);
    bufp->fullIData(oldp+277,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[28]),32);
    bufp->fullIData(oldp+278,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[29]),32);
    bufp->fullIData(oldp+279,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[30]),32);
    bufp->fullIData(oldp+280,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern[31]),32);
    bufp->fullIData(oldp+281,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[0]),32);
    bufp->fullIData(oldp+282,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[1]),32);
    bufp->fullIData(oldp+283,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[2]),32);
    bufp->fullIData(oldp+284,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[3]),32);
    bufp->fullIData(oldp+285,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[4]),32);
    bufp->fullIData(oldp+286,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[5]),32);
    bufp->fullIData(oldp+287,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[6]),32);
    bufp->fullIData(oldp+288,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[7]),32);
    bufp->fullIData(oldp+289,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[8]),32);
    bufp->fullIData(oldp+290,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[9]),32);
    bufp->fullIData(oldp+291,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[10]),32);
    bufp->fullIData(oldp+292,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[11]),32);
    bufp->fullIData(oldp+293,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[12]),32);
    bufp->fullIData(oldp+294,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[13]),32);
    bufp->fullIData(oldp+295,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[14]),32);
    bufp->fullIData(oldp+296,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[15]),32);
    bufp->fullIData(oldp+297,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[16]),32);
    bufp->fullIData(oldp+298,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[17]),32);
    bufp->fullIData(oldp+299,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[18]),32);
    bufp->fullIData(oldp+300,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[19]),32);
    bufp->fullIData(oldp+301,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[20]),32);
    bufp->fullIData(oldp+302,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[21]),32);
    bufp->fullIData(oldp+303,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[22]),32);
    bufp->fullIData(oldp+304,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[23]),32);
    bufp->fullIData(oldp+305,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[24]),32);
    bufp->fullIData(oldp+306,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[25]),32);
    bufp->fullIData(oldp+307,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[26]),32);
    bufp->fullIData(oldp+308,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[27]),32);
    bufp->fullIData(oldp+309,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[28]),32);
    bufp->fullIData(oldp+310,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[29]),32);
    bufp->fullIData(oldp+311,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[30]),32);
    bufp->fullIData(oldp+312,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask[31]),32);
    bufp->fullIData(oldp+313,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__latched_fifo_data),32);
    bufp->fullBit(oldp+314,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__latched_data_valid));
    bufp->fullBit(oldp+315,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__sending_valid_fifo_data));
    bufp->fullIData(oldp+316,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__i),32);
    bufp->fullIData(oldp+317,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__byte_index),32);
    bufp->fullBit(oldp+318,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__slv_reg_wren));
    bufp->fullSData(oldp+319,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__write_pat_offset),12);
    bufp->fullSData(oldp+320,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__write_mask_offset),12);
    bufp->fullSData(oldp+321,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__read_pat_offset),12);
    bufp->fullSData(oldp+322,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__read_mask_offset),12);
    bufp->fullBit(oldp+323,(vlSelfRef.top_slave_module__DOT__u_axi_lite_regs__DOT__cpu_reads_fifo));
    bufp->fullBit(oldp+324,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__clk));
    bufp->fullBit(oldp+325,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__rst_n));
    bufp->fullIData(oldp+326,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__data_in),32);
    bufp->fullBit(oldp+327,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__wr_en));
    bufp->fullBit(oldp+328,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__rd_en));
    bufp->fullIData(oldp+329,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__data_out),32);
    bufp->fullBit(oldp+330,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__empty));
    bufp->fullCData(oldp+331,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__count_out),5);
    bufp->fullIData(oldp+332,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[0]),32);
    bufp->fullIData(oldp+333,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[1]),32);
    bufp->fullIData(oldp+334,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[2]),32);
    bufp->fullIData(oldp+335,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[3]),32);
    bufp->fullIData(oldp+336,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[4]),32);
    bufp->fullIData(oldp+337,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[5]),32);
    bufp->fullIData(oldp+338,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[6]),32);
    bufp->fullIData(oldp+339,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[7]),32);
    bufp->fullIData(oldp+340,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[8]),32);
    bufp->fullIData(oldp+341,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[9]),32);
    bufp->fullIData(oldp+342,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[10]),32);
    bufp->fullIData(oldp+343,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[11]),32);
    bufp->fullIData(oldp+344,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[12]),32);
    bufp->fullIData(oldp+345,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[13]),32);
    bufp->fullIData(oldp+346,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[14]),32);
    bufp->fullIData(oldp+347,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__mem[15]),32);
    bufp->fullCData(oldp+348,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__wr_ptr),4);
    bufp->fullCData(oldp+349,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__rd_ptr),4);
    bufp->fullCData(oldp+350,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__count),5);
    bufp->fullBit(oldp+351,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__wr_allowed));
    bufp->fullBit(oldp+352,(vlSelfRef.top_slave_module__DOT__u_hits_fifo__DOT__rd_allowed));
    bufp->fullBit(oldp+353,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__clk));
    bufp->fullBit(oldp+354,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__rst_n));
    bufp->fullIData(oldp+355,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__s_axis_tdata),32);
    bufp->fullCData(oldp+356,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__s_axis_tkeep),4);
    bufp->fullBit(oldp+357,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__s_axis_tvalid));
    bufp->fullBit(oldp+358,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__s_axis_tready));
    bufp->fullBit(oldp+359,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__s_axis_tlast));
    bufp->fullCData(oldp+360,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__m_axis_tdata),8);
    bufp->fullBit(oldp+361,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__m_axis_tvalid));
    bufp->fullBit(oldp+362,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__m_axis_tlast));
    bufp->fullBit(oldp+363,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__m_axis_tready));
    bufp->fullIData(oldp+364,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__buf_data),32);
    bufp->fullCData(oldp+365,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__buf_keep),4);
    bufp->fullBit(oldp+366,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__buf_last));
    bufp->fullCData(oldp+367,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__buf_idx),2);
    bufp->fullBit(oldp+368,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__buf_valid));
    bufp->fullCData(oldp+369,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__max_idx),2);
    bufp->fullBit(oldp+370,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__is_last_byte));
    bufp->fullBit(oldp+371,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__pipe_advance));
    bufp->fullCData(oldp+372,(vlSelfRef.top_slave_module__DOT__u_stream_gearbox__DOT__ext_byte),8);
    bufp->fullBit(oldp+373,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__clk));
    bufp->fullBit(oldp+374,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__rst_n));
    bufp->fullCData(oldp+375,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__s_axis_tdata),8);
    bufp->fullBit(oldp+376,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__s_axis_tvalid));
    bufp->fullBit(oldp+377,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__s_axis_tready));
    bufp->fullBit(oldp+378,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__s_axis_tlast));
    bufp->fullCData(oldp+379,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__m_axis_tdata),8);
    bufp->fullBit(oldp+380,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__m_axis_tvalid));
    bufp->fullBit(oldp+381,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__m_axis_tlast));
    bufp->fullIData(oldp+382,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__m_current_pos),32);
    bufp->fullBit(oldp+383,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__m_axis_tready));
    bufp->fullBit(oldp+384,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__encoding_error));
    bufp->fullIData(oldp+385,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__error_position),32);
    bufp->fullIData(oldp+386,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__final_char_count),32);
    bufp->fullBit(oldp+387,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__char_count_valid));
    bufp->fullBit(oldp+388,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__pipe_advance));
    bufp->fullCData(oldp+389,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__utf8_state),2);
    bufp->fullIData(oldp+390,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__char_pos_counter),32);
    bufp->fullBit(oldp+391,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__is_new_file));
    bufp->fullBit(oldp+392,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__expect_e0));
    bufp->fullBit(oldp+393,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__expect_ed));
    bufp->fullBit(oldp+394,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__expect_f0));
    bufp->fullBit(oldp+395,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__expect_f4));
    bufp->fullCData(oldp+396,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__active_state),2);
    bufp->fullIData(oldp+397,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__active_pos),32);
    bufp->fullBit(oldp+398,(vlSelfRef.top_slave_module__DOT__u_stream_validator__DOT__char_completes_this_byte));
    bufp->fullBit(oldp+399,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__clk));
    bufp->fullBit(oldp+400,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__rst_n));
    bufp->fullBit(oldp+401,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__s_axis_tvalid));
    bufp->fullCData(oldp+402,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__s_axis_tdata),8);
    bufp->fullIData(oldp+403,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__s_axis_tpos),32);
    bufp->fullBit(oldp+404,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__s_axis_tlast));
    bufp->fullBit(oldp+405,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__s_axis_tready));
    bufp->fullWData(oldp+406,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__pattern_in),1024);
    bufp->fullWData(oldp+438,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__mask_in),1024);
    bufp->fullCData(oldp+470,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__pattern_len),8);
    bufp->fullBit(oldp+471,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__matcher_active));
    bufp->fullIData(oldp+472,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__hit_data_out),32);
    bufp->fullBit(oldp+473,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__hit_valid_out));
    bufp->fullCData(oldp+474,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__fifo_count_in),5);
    bufp->fullIData(oldp+475,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__match_count),32);
    bufp->fullBit(oldp+476,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__match_count_valid));
    bufp->fullCData(oldp+477,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__state),2);
    bufp->fullCData(oldp+478,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__next_state),2);
    bufp->fullCData(oldp+479,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__flush_counter),3);
    bufp->fullWData(oldp+480,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__shift_reg),1024);
    bufp->fullIData(oldp+512,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__data_in_fifo),32);
    bufp->fullBit(oldp+513,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__match_found));
    bufp->fullIData(oldp+514,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__pos_pipe[0]),32);
    bufp->fullIData(oldp+515,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__pos_pipe[1]),32);
    bufp->fullIData(oldp+516,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__pos_pipe[2]),32);
    bufp->fullIData(oldp+517,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__pos_pipe[3]),32);
    bufp->fullIData(oldp+518,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__pattern_start_offset),32);
    bufp->fullBit(oldp+519,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__clk_en_latch));
    bufp->fullBit(oldp+520,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__shift_reg_valid));
    bufp->fullIData(oldp+521,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__i),32);
    bufp->fullBit(oldp+522,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__match_out));
    bufp->fullBit(oldp+523,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__ready_to_accept));
    bufp->fullBit(oldp+524,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__s_axis_txfer));
    bufp->fullIData(oldp+525,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__pattern_len_ext),32);
    bufp->fullIData(oldp+526,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__const_one),32);
    bufp->fullQData(oldp+527,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__pos_diff_ext),33);
    bufp->fullBit(oldp+529,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__datapath_active));
    bufp->fullBit(oldp+530,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__clk_gated));
    bufp->fullBit(oldp+531,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__clk));
    bufp->fullBit(oldp+532,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__rst_n));
    bufp->fullWData(oldp+533,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__shift_reg),1024);
    bufp->fullWData(oldp+565,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__pattern_in),1024);
    bufp->fullWData(oldp+597,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__mask_in),1024);
    bufp->fullBit(oldp+629,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__data_valid));
    bufp->fullBit(oldp+630,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__match_out));
    bufp->fullWData(oldp+631,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__mismatch),1024);
    bufp->fullCData(oldp+663,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__chunk_match),8);
    bufp->fullCData(oldp+664,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__valid_pipe),2);
    bufp->fullIData(oldp+665,(vlSelfRef.top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__i),32);
}
