// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_cov.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(S_AXI_ACLK,0,0);
        VL_IN8(S_AXI_ARESETN,0,0);
        VL_IN8(S_AXI_AWVALID,0,0);
        VL_OUT8(S_AXI_AWREADY,0,0);
        VL_IN8(S_AXI_WSTRB,3,0);
        VL_IN8(S_AXI_WVALID,0,0);
        VL_OUT8(S_AXI_WREADY,0,0);
        VL_OUT8(S_AXI_BRESP,1,0);
        VL_OUT8(S_AXI_BVALID,0,0);
        VL_IN8(S_AXI_BREADY,0,0);
        VL_IN8(S_AXI_ARVALID,0,0);
        VL_OUT8(S_AXI_ARREADY,0,0);
        VL_OUT8(S_AXI_RRESP,1,0);
        VL_OUT8(S_AXI_RVALID,0,0);
        VL_IN8(S_AXI_RREADY,0,0);
        VL_IN8(S_AXIS_TKEEP,3,0);
        VL_IN8(S_AXIS_TLAST,0,0);
        VL_IN8(S_AXIS_TVALID,0,0);
        VL_OUT8(S_AXIS_TREADY,0,0);
        CData/*0:0*/ top_slave_module__DOT__S_AXI_ACLK;
        CData/*0:0*/ top_slave_module__DOT__S_AXI_ARESETN;
        CData/*0:0*/ top_slave_module__DOT__S_AXI_AWVALID;
        CData/*0:0*/ top_slave_module__DOT__S_AXI_AWREADY;
        CData/*3:0*/ top_slave_module__DOT__S_AXI_WSTRB;
        CData/*0:0*/ top_slave_module__DOT__S_AXI_WVALID;
        CData/*0:0*/ top_slave_module__DOT__S_AXI_WREADY;
        CData/*1:0*/ top_slave_module__DOT__S_AXI_BRESP;
        CData/*0:0*/ top_slave_module__DOT__S_AXI_BVALID;
        CData/*0:0*/ top_slave_module__DOT__S_AXI_BREADY;
        CData/*0:0*/ top_slave_module__DOT__S_AXI_ARVALID;
        CData/*0:0*/ top_slave_module__DOT__S_AXI_ARREADY;
        CData/*1:0*/ top_slave_module__DOT__S_AXI_RRESP;
        CData/*0:0*/ top_slave_module__DOT__S_AXI_RVALID;
        CData/*0:0*/ top_slave_module__DOT__S_AXI_RREADY;
        CData/*3:0*/ top_slave_module__DOT__S_AXIS_TKEEP;
        CData/*0:0*/ top_slave_module__DOT__S_AXIS_TLAST;
        CData/*0:0*/ top_slave_module__DOT__S_AXIS_TVALID;
        CData/*0:0*/ top_slave_module__DOT__S_AXIS_TREADY;
        CData/*0:0*/ top_slave_module__DOT__rst_n_meta;
        CData/*0:0*/ top_slave_module__DOT__rst_n_sync;
        CData/*0:0*/ top_slave_module__DOT__sys_rst_n;
        CData/*1:0*/ top_slave_module__DOT__sig_operation_mode;
        CData/*0:0*/ top_slave_module__DOT__sig_char_count_valid;
        CData/*0:0*/ top_slave_module__DOT__sig_encoding_error;
        CData/*0:0*/ top_slave_module__DOT__sig_match_count_valid;
        CData/*0:0*/ top_slave_module__DOT__sig_fifo_empty;
        CData/*0:0*/ top_slave_module__DOT__sig_fifo_rd_en;
        CData/*7:0*/ top_slave_module__DOT__sig_pattern_len;
        CData/*7:0*/ top_slave_module__DOT__gb_tdata;
        CData/*0:0*/ top_slave_module__DOT__gb_tvalid;
        CData/*0:0*/ top_slave_module__DOT__gb_tready;
        CData/*0:0*/ top_slave_module__DOT__gb_tlast;
        CData/*7:0*/ top_slave_module__DOT__val_tdata;
        CData/*0:0*/ top_slave_module__DOT__val_tvalid;
        CData/*0:0*/ top_slave_module__DOT__val_tready;
        CData/*0:0*/ top_slave_module__DOT__val_tlast;
        CData/*0:0*/ top_slave_module__DOT__matcher_en;
        CData/*0:0*/ top_slave_module__DOT__matcher_tvalid;
        CData/*7:0*/ top_slave_module__DOT__matcher_tdata;
        CData/*0:0*/ top_slave_module__DOT__matcher_tlast;
        CData/*0:0*/ top_slave_module__DOT__matcher_tready;
        CData/*0:0*/ top_slave_module__DOT__hit_valid_wire;
        CData/*4:0*/ top_slave_module__DOT__fifo_count_wire;
        CData/*0:0*/ top_slave_module__DOT__fifo_wr_en;
    };
    struct {
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXI_ACLK;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXI_ARESETN;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXI_AWVALID;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXI_AWREADY;
        CData/*3:0*/ top_slave_module__DOT____Vtogcov__S_AXI_WSTRB;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXI_WVALID;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXI_WREADY;
        CData/*1:0*/ top_slave_module__DOT____Vtogcov__S_AXI_BRESP;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXI_BVALID;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXI_BREADY;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXI_ARVALID;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXI_ARREADY;
        CData/*1:0*/ top_slave_module__DOT____Vtogcov__S_AXI_RRESP;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXI_RVALID;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXI_RREADY;
        CData/*3:0*/ top_slave_module__DOT____Vtogcov__S_AXIS_TKEEP;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXIS_TLAST;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXIS_TVALID;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__S_AXIS_TREADY;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__rst_n_meta;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__rst_n_sync;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__sys_rst_n;
        CData/*1:0*/ top_slave_module__DOT____Vtogcov__sig_operation_mode;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__sig_char_count_valid;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__sig_encoding_error;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__sig_match_count_valid;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__sig_fifo_empty;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__sig_fifo_rd_en;
        CData/*7:0*/ top_slave_module__DOT____Vtogcov__sig_pattern_len;
        CData/*7:0*/ top_slave_module__DOT____Vtogcov__gb_tdata;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__gb_tvalid;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__gb_tready;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__gb_tlast;
        CData/*7:0*/ top_slave_module__DOT____Vtogcov__val_tdata;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__val_tvalid;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__val_tready;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__val_tlast;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__matcher_en;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__matcher_tvalid;
        CData/*7:0*/ top_slave_module__DOT____Vtogcov__matcher_tdata;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__matcher_tlast;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__matcher_tready;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__hit_valid_wire;
        CData/*4:0*/ top_slave_module__DOT____Vtogcov__fifo_count_wire;
        CData/*0:0*/ top_slave_module__DOT____Vtogcov__fifo_wr_en;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_ACLK;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_ARESETN;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_AWVALID;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_AWREADY;
        CData/*3:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_WSTRB;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_WVALID;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_WREADY;
        CData/*1:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_BRESP;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_BVALID;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_BREADY;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_ARVALID;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_ARREADY;
        CData/*1:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_RRESP;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_RVALID;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_RREADY;
        CData/*1:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__operation_mode;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__char_count_valid;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__encoding_error;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__match_count_valid;
    };
    struct {
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__fifo_empty;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__fifo_rd_en;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__axi_awready;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__axi_wready;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__axi_bvalid;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__axi_arready;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__axi_rvalid;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__latched_data_valid;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__sending_valid_fifo_data;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__slv_reg_wren;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__cpu_reads_fifo;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_ACLK;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_ARESETN;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_AWVALID;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_AWREADY;
        CData/*3:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_WSTRB;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_WVALID;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_WREADY;
        CData/*1:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_BRESP;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_BVALID;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_BREADY;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_ARVALID;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_ARREADY;
        CData/*1:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_RRESP;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_RVALID;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_RREADY;
        CData/*1:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__operation_mode;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__char_count_valid;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__encoding_error;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__match_count_valid;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__fifo_empty;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__fifo_rd_en;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__axi_awready;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__axi_wready;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__axi_bvalid;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__axi_arready;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__axi_rvalid;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__latched_data_valid;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__sending_valid_fifo_data;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__slv_reg_wren;
        CData/*0:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__cpu_reads_fifo;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__clk;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__rst_n;
        CData/*3:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__s_axis_tkeep;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__s_axis_tvalid;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__s_axis_tready;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__s_axis_tlast;
        CData/*7:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__m_axis_tdata;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__m_axis_tvalid;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__m_axis_tlast;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__m_axis_tready;
        CData/*3:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__buf_keep;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__buf_last;
        CData/*1:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__buf_idx;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__buf_valid;
        CData/*1:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__max_idx;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__is_last_byte;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__pipe_advance;
        CData/*7:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__ext_byte;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__clk;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__rst_n;
        CData/*3:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__s_axis_tkeep;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__s_axis_tvalid;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__s_axis_tready;
    };
    struct {
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__s_axis_tlast;
        CData/*7:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__m_axis_tdata;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__m_axis_tvalid;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__m_axis_tlast;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__m_axis_tready;
        CData/*3:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__buf_keep;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__buf_last;
        CData/*1:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__buf_idx;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__buf_valid;
        CData/*1:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__max_idx;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__is_last_byte;
        CData/*0:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__pipe_advance;
        CData/*7:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__ext_byte;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__clk;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__rst_n;
        CData/*7:0*/ top_slave_module__DOT__u_stream_validator__DOT__s_axis_tdata;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__s_axis_tvalid;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__s_axis_tready;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__s_axis_tlast;
        CData/*7:0*/ top_slave_module__DOT__u_stream_validator__DOT__m_axis_tdata;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__m_axis_tvalid;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__m_axis_tlast;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__m_axis_tready;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__encoding_error;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__char_count_valid;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__pipe_advance;
        CData/*1:0*/ top_slave_module__DOT__u_stream_validator__DOT__utf8_state;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__is_new_file;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__expect_e0;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__expect_ed;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__expect_f0;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__expect_f4;
        CData/*1:0*/ top_slave_module__DOT__u_stream_validator__DOT__active_state;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT__char_completes_this_byte;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__clk;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__rst_n;
        CData/*7:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__s_axis_tdata;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__s_axis_tvalid;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__s_axis_tready;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__s_axis_tlast;
        CData/*7:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__m_axis_tdata;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__m_axis_tvalid;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__m_axis_tlast;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__m_axis_tready;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__encoding_error;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__char_count_valid;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__pipe_advance;
        CData/*1:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__utf8_state;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__is_new_file;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__expect_e0;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__expect_ed;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__expect_f0;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__expect_f4;
        CData/*1:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__active_state;
        CData/*0:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__char_completes_this_byte;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__clk;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__rst_n;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__s_axis_tvalid;
        CData/*7:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__s_axis_tdata;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__s_axis_tlast;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__s_axis_tready;
        CData/*7:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__pattern_len;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__matcher_active;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__hit_valid_out;
    };
    struct {
        CData/*4:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__fifo_count_in;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__match_count_valid;
        CData/*1:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__state;
        CData/*1:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__next_state;
        CData/*2:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__flush_counter;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__match_found;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__clk_en_latch;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__shift_reg_valid;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__match_out;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__ready_to_accept;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__s_axis_txfer;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__datapath_active;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__clk_gated;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__clk;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__rst_n;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__s_axis_tvalid;
        CData/*7:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__s_axis_tdata;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__s_axis_tlast;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__s_axis_tready;
        CData/*7:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__pattern_len;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__matcher_active;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__hit_valid_out;
        CData/*4:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__fifo_count_in;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__match_count_valid;
        CData/*1:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__state;
        CData/*1:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__next_state;
        CData/*2:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__flush_counter;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__match_found;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__clk_en_latch;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__shift_reg_valid;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__match_out;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__ready_to_accept;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__s_axis_txfer;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__datapath_active;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__clk_gated;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__clk;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__rst_n;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__data_valid;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__match_out;
        CData/*7:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__chunk_match;
        CData/*1:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__valid_pipe;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT____Vtogcov__clk;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT____Vtogcov__rst_n;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT____Vtogcov__data_valid;
        CData/*0:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT____Vtogcov__match_out;
        CData/*7:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT____Vtogcov__chunk_match;
        CData/*1:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT____Vtogcov__valid_pipe;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT__clk;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT__rst_n;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT__wr_en;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT__rd_en;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT__empty;
        CData/*4:0*/ top_slave_module__DOT__u_hits_fifo__DOT__count_out;
        CData/*3:0*/ top_slave_module__DOT__u_hits_fifo__DOT__wr_ptr;
        CData/*3:0*/ top_slave_module__DOT__u_hits_fifo__DOT__rd_ptr;
        CData/*4:0*/ top_slave_module__DOT__u_hits_fifo__DOT__count;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT__wr_allowed;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT__rd_allowed;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__clk;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__rst_n;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__wr_en;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__rd_en;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__empty;
        CData/*4:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__count_out;
    };
    struct {
        CData/*3:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__wr_ptr;
        CData/*3:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__rd_ptr;
        CData/*4:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__count;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__wr_allowed;
        CData/*0:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__rd_allowed;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__top_slave_module__DOT__S_AXI_ACLK__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_ACLK__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__top_slave_module__DOT__u_stream_gearbox__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__top_slave_module__DOT__u_stream_validator__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__top_slave_module__DOT__u_subchar_matcher__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__top_slave_module__DOT__u_subchar_matcher__DOT__clk_gated__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__top_slave_module__DOT__u_hits_fifo__DOT__clk__0;
        VL_IN16(S_AXI_AWADDR,11,0);
        VL_IN16(S_AXI_ARADDR,11,0);
        SData/*11:0*/ top_slave_module__DOT__S_AXI_AWADDR;
        SData/*11:0*/ top_slave_module__DOT__S_AXI_ARADDR;
        SData/*11:0*/ top_slave_module__DOT____Vtogcov__S_AXI_AWADDR;
        SData/*11:0*/ top_slave_module__DOT____Vtogcov__S_AXI_ARADDR;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_AWADDR;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_ARADDR;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__awaddr;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__axi_araddr_reg;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__write_pat_offset;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__write_mask_offset;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__read_pat_offset;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__read_mask_offset;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_AWADDR;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_ARADDR;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__awaddr;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__axi_araddr_reg;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__write_pat_offset;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__write_mask_offset;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__read_pat_offset;
        SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__read_mask_offset;
        VL_IN(S_AXI_WDATA,31,0);
        VL_OUT(S_AXI_RDATA,31,0);
        VL_IN(S_AXIS_TDATA,31,0);
        IData/*31:0*/ top_slave_module__DOT__S_AXI_WDATA;
        IData/*31:0*/ top_slave_module__DOT__S_AXI_RDATA;
        IData/*31:0*/ top_slave_module__DOT__S_AXIS_TDATA;
        VlWide<32>/*1023:0*/ top_slave_module__DOT__sig_pattern_in;
        VlWide<32>/*1023:0*/ top_slave_module__DOT__sig_mask_in;
        IData/*31:0*/ top_slave_module__DOT__sig_pattern_len_full;
        IData/*31:0*/ top_slave_module__DOT__sig_final_char_count;
        IData/*31:0*/ top_slave_module__DOT__sig_error_position;
        IData/*31:0*/ top_slave_module__DOT__sig_match_count;
        IData/*31:0*/ top_slave_module__DOT__sig_fifo_data_out;
        IData/*31:0*/ top_slave_module__DOT__val_tpos;
        IData/*31:0*/ top_slave_module__DOT__matcher_tpos;
        IData/*31:0*/ top_slave_module__DOT__hit_data_wire;
        IData/*31:0*/ top_slave_module__DOT____Vtogcov__S_AXI_WDATA;
        IData/*31:0*/ top_slave_module__DOT____Vtogcov__S_AXI_RDATA;
        IData/*31:0*/ top_slave_module__DOT____Vtogcov__S_AXIS_TDATA;
        IData/*31:0*/ top_slave_module__DOT____Vtogcov__sig_pattern_len_full;
        IData/*31:0*/ top_slave_module__DOT____Vtogcov__sig_final_char_count;
        IData/*31:0*/ top_slave_module__DOT____Vtogcov__sig_error_position;
        IData/*31:0*/ top_slave_module__DOT____Vtogcov__sig_match_count;
        IData/*31:0*/ top_slave_module__DOT____Vtogcov__sig_fifo_data_out;
        IData/*31:0*/ top_slave_module__DOT____Vtogcov__val_tpos;
        IData/*31:0*/ top_slave_module__DOT____Vtogcov__matcher_tpos;
        IData/*31:0*/ top_slave_module__DOT____Vtogcov__hit_data_wire;
    };
    struct {
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_WDATA;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__S_AXI_RDATA;
        VlWide<32>/*1023:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__pattern_in;
        VlWide<32>/*1023:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__mask_in;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__pattern_len;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__final_char_count;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__error_position;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__match_count;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__fifo_data_out;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__axi_rdata;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__latched_fifo_data;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__i;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__byte_index;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_WDATA;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__S_AXI_RDATA;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__pattern_len;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__final_char_count;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__error_position;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__match_count;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__fifo_data_out;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__axi_rdata;
        IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT____Vtogcov__latched_fifo_data;
        IData/*31:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__s_axis_tdata;
        IData/*31:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__buf_data;
        IData/*31:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__s_axis_tdata;
        IData/*31:0*/ top_slave_module__DOT__u_stream_gearbox__DOT____Vtogcov__buf_data;
        IData/*31:0*/ top_slave_module__DOT__u_stream_validator__DOT__m_current_pos;
        IData/*31:0*/ top_slave_module__DOT__u_stream_validator__DOT__error_position;
        IData/*31:0*/ top_slave_module__DOT__u_stream_validator__DOT__final_char_count;
        IData/*31:0*/ top_slave_module__DOT__u_stream_validator__DOT__char_pos_counter;
        IData/*31:0*/ top_slave_module__DOT__u_stream_validator__DOT__active_pos;
        IData/*31:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__m_current_pos;
        IData/*31:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__error_position;
        IData/*31:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__final_char_count;
        IData/*31:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__char_pos_counter;
        IData/*31:0*/ top_slave_module__DOT__u_stream_validator__DOT____Vtogcov__active_pos;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__s_axis_tpos;
        VlWide<32>/*1023:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__pattern_in;
        VlWide<32>/*1023:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__mask_in;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__hit_data_out;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__match_count;
        VlWide<32>/*1023:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__shift_reg;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__data_in_fifo;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__pattern_start_offset;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__i;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__pattern_len_ext;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__const_one;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__s_axis_tpos;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__hit_data_out;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__match_count;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__data_in_fifo;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__pattern_start_offset;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__pattern_len_ext;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__const_one;
        VlWide<32>/*1023:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__shift_reg;
        VlWide<32>/*1023:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__pattern_in;
        VlWide<32>/*1023:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__mask_in;
        VlWide<32>/*1023:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__mismatch;
        IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__i;
        IData/*31:0*/ top_slave_module__DOT__u_hits_fifo__DOT__data_in;
        IData/*31:0*/ top_slave_module__DOT__u_hits_fifo__DOT__data_out;
        IData/*31:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__data_in;
        IData/*31:0*/ top_slave_module__DOT__u_hits_fifo__DOT____Vtogcov__data_out;
        IData/*31:0*/ __VactIterCount;
    };
    struct {
        QData/*32:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__pos_diff_ext;
        QData/*32:0*/ top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__pos_diff_ext;
        VlUnpacked<IData/*31:0*/, 32> top_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern;
        VlUnpacked<IData/*31:0*/, 32> top_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask;
        VlUnpacked<IData/*31:0*/, 4> top_slave_module__DOT__u_subchar_matcher__DOT__pos_pipe;
        VlUnpacked<IData/*31:0*/, 4> top_slave_module__DOT__u_subchar_matcher__DOT____Vtogcov__pos_pipe;
        VlUnpacked<IData/*31:0*/, 16> top_slave_module__DOT__u_hits_fifo__DOT__mem;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<IData/*31:0*/, 32>, true, IData/*31:0*/, 1> __VdlyCommitQueuetop_slave_module__DOT__u_axi_lite_regs__DOT__reg_pattern;
    VlNBACommitQueue<VlUnpacked<IData/*31:0*/, 32>, true, IData/*31:0*/, 1> __VdlyCommitQueuetop_slave_module__DOT__u_axi_lite_regs__DOT__reg_mask;
    VlNBACommitQueue<VlUnpacked<IData/*31:0*/, 4>, false, IData/*31:0*/, 1> __VdlyCommitQueuetop_slave_module__DOT__u_subchar_matcher__DOT__pos_pipe;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*1:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__IDLE = 0U;
    static constexpr CData/*1:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__RUNNING = 1U;
    static constexpr CData/*1:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__PAUSED = 2U;
    static constexpr CData/*1:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__FLUSHING = 3U;
    static constexpr SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__ADDR_PATTERN_BASE = 0x0100U;
    static constexpr SData/*11:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__ADDR_MASK_BASE = 0x0200U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__C_S_AXI_DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__C_S_AXI_ADDR_WIDTH = 0x0000000cU;
    static constexpr IData/*31:0*/ top_slave_module__DOT__PATTERN_WIDTH = 0x00000400U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__POS_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__DATA_WIDTH = 8U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__FIFO_DEPTH = 0x00000010U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__MATCH_LATENCY = 6U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__C_S_AXI_DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__C_S_AXI_ADDR_WIDTH = 0x0000000cU;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__PATTERN_WIDTH = 0x00000400U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__POS_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__PATTERN_REGS = 0x00000020U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__PATTERN_IDX_W = 5U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__ADDR_SHIFT = 2U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__ADDR_PATTERN_HIGH = 0x00000180U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_axi_lite_regs__DOT__ADDR_MASK_HIGH = 0x00000280U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__DATA_IN_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__DATA_OUT_WIDTH = 8U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_stream_gearbox__DOT__KEEP_WIDTH = 4U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_stream_validator__DOT__DATA_WIDTH = 8U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_stream_validator__DOT__POS_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__DATA_WIDTH = 8U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__FIFO_DEPTH = 0x00000010U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__PATTERN_WIDTH = 0x00000400U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__POS_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__MATCH_LATENCY = 6U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__FLUSH_TARGET = 5U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__FLUSH_CNT_W = 3U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__PAT_LEN_W = 8U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__WIDTH = 0x00000400U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__CHUNK_SIZE = 0x00000080U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_subchar_matcher__DOT__wide_comparator_inst__DOT__CHUNKS = 8U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_hits_fifo__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top_slave_module__DOT__u_hits_fifo__DOT__FIFO_DEPTH = 0x00000010U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __vlCoverInsert(uint32_t* countp, bool enable, const char* filenamep, int lineno, int column,
        const char* hierp, const char* pagep, const char* commentp, const char* linescovp);
    void __vlCoverToggleInsert(int begin, int end, bool ranged, uint32_t* countp, bool enable, const char* filenamep, int lineno, int column,
        const char* hierp, const char* pagep, const char* commentp);
};


#endif  // guard
